// thortful-workshop/src/app/components/cart/cart.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CartService } from '../../services/cart.service';
import { type CartItemsObjectResponse } from '@epcc-sdk/sdks-shopper';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="cart-container">
      <h2>Shopping Cart</h2>
      
      <div *ngIf="(cartService.loading$ | async)" class="loading">
        Loading cart...
      </div>
      
      <div *ngIf="(cartService.error$ | async) as error" class="error">
        {{ error }}
      </div>
      
      <div *ngIf="!(cartService.loading$ | async)" class="cart-content">
        <div class="cart-items">
          <h3>Items ({{ cartService.itemCount$ | async }})</h3>
          
          <div *ngIf="(cartService.items$ | async)?.length === 0" class="empty-cart">
            Your cart is empty
          </div>
          
          <ng-container *ngFor="let item of (cartService.items$ | async)">
          <div class="cart-item" *ngIf="isCartItem(item)">
            <div class="item-image" *ngIf="hasImage(item)">
              <img [src]="getImage(item)?.href" [alt]="item.name">
            </div>
            
            <div class="item-details">
              <h4>{{ item.name }}</h4>
              <p class="sku" *ngIf="hasSku(item)">SKU: {{ getSku(item) }}</p>
              <p class="price">{{ getUnitPrice(item) }}</p>
            </div>
            
            <div class="item-quantity">
              <button (click)="updateQuantity(item.id || '', getQuantity(item) - 1)" 
                      [disabled]="getQuantity(item) <= 1">-</button>
              <span>{{ getQuantity(item) }}</span>
              <button (click)="updateQuantity(item.id || '', getQuantity(item) + 1)">+</button>
            </div>
            
            <div class="item-total">
              {{ getTotalPrice(item) }}
            </div>
            
            <button class="remove-btn" (click)="removeItem(item.id || '')">Remove</button>
          </div>
          </ng-container>
        </div>
        
        <div class="cart-summary">
          <h3>Order Summary</h3>
          
          <div class="totals" *ngIf="(cartService.totals$ | async) as totals">
            <div class="total-line">
              <span>Subtotal:</span>
              <span>{{ totals.subtotal }}</span>
            </div>
            
            <div class="total-line" *ngIf="totals.hasDiscount">
              <span>Discount:</span>
              <span class="discount">{{ totals.discount }}</span>
            </div>
            
            <div class="total-line" *ngIf="totals.shipping !== '$0.00'">
              <span>Shipping:</span>
              <span>{{ totals.shipping }}</span>
            </div>
            
            <div class="total-line">
              <span>Tax:</span>
              <span>{{ totals.tax }}</span>
            </div>
            
            <div class="total-line total">
              <span>Total:</span>
              <span>{{ totals.total }}</span>
            </div>
          </div>
          
          <div class="promo-code">
            <h4>Promo Code</h4>
            <div class="promo-input">
              <input type="text" 
                     [(ngModel)]="promoCode" 
                     placeholder="Enter promo code"
                     (keyup.enter)="applyPromoCode()">
              <button (click)="applyPromoCode()" [disabled]="!promoCode">Apply</button>
            </div>
          </div>
          
          <button class="checkout-btn" 
                  [disabled]="(cartService.itemCount$ | async) === 0">
            Proceed to Checkout
          </button>
        </div>
      </div>
      
      <div class="test-section">
        <h3>Test Cart Operations</h3>
        <div class="test-actions">
          <button (click)="addTestProduct()">Add Test Product</button>
          <button (click)="clearCart()">Clear Cart</button>
          <button (click)="refreshCart()">Refresh Cart</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .cart-container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }
    
    .loading, .error {
      padding: 20px;
      text-align: center;
    }
    
    .error {
      color: #dc3545;
    }
    
    .cart-content {
      display: grid;
      grid-template-columns: 1fr 400px;
      gap: 40px;
      margin-top: 20px;
    }
    
    .cart-items {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
    }
    
    .empty-cart {
      padding: 40px;
      text-align: center;
      color: #6c757d;
    }
    
    .cart-item {
      display: grid;
      grid-template-columns: 100px 1fr auto auto auto;
      gap: 20px;
      align-items: center;
      padding: 20px;
      background: white;
      margin-bottom: 10px;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    
    .item-image img {
      width: 100%;
      height: 100px;
      object-fit: cover;
      border-radius: 4px;
    }
    
    .item-details h4 {
      margin: 0 0 5px 0;
    }
    
    .item-details p {
      margin: 0;
      color: #6c757d;
    }
    
    .item-quantity {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    
    .item-quantity button {
      width: 30px;
      height: 30px;
      border: 1px solid #ddd;
      background: white;
      cursor: pointer;
      border-radius: 4px;
    }
    
    .item-quantity button:hover:not(:disabled) {
      background: #f8f9fa;
    }
    
    .item-quantity button:disabled {
      cursor: not-allowed;
      opacity: 0.5;
    }
    
    .item-total {
      font-weight: 600;
    }
    
    .remove-btn {
      background: none;
      border: none;
      color: #dc3545;
      cursor: pointer;
      text-decoration: underline;
    }
    
    .cart-summary {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      height: fit-content;
      position: sticky;
      top: 20px;
    }
    
    .cart-summary h3 {
      margin-top: 0;
    }
    
    .totals {
      margin: 20px 0;
    }
    
    .total-line {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e9ecef;
    }
    
    .total-line.total {
      font-size: 1.2em;
      font-weight: 600;
      border-bottom: none;
      border-top: 2px solid #dee2e6;
      margin-top: 10px;
      padding-top: 15px;
    }
    
    .discount {
      color: #28a745;
    }
    
    .promo-code {
      margin: 20px 0;
    }
    
    .promo-code h4 {
      margin-bottom: 10px;
    }
    
    .promo-input {
      display: flex;
      gap: 10px;
    }
    
    .promo-input input {
      flex: 1;
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
    }
    
    .promo-input button {
      padding: 8px 20px;
      background: #6c757d;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    
    .promo-input button:hover:not(:disabled) {
      background: #5a6268;
    }
    
    .promo-input button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
    
    .checkout-btn {
      width: 100%;
      padding: 15px;
      background: #007bff;
      color: white;
      border: none;
      border-radius: 4px;
      font-size: 1.1em;
      cursor: pointer;
    }
    
    .checkout-btn:hover:not(:disabled) {
      background: #0056b3;
    }
    
    .checkout-btn:disabled {
      background: #6c757d;
      cursor: not-allowed;
    }
    
    .test-section {
      margin-top: 40px;
      padding: 20px;
      background: #e9ecef;
      border-radius: 8px;
    }
    
    .test-actions {
      display: flex;
      gap: 10px;
      margin-top: 10px;
    }
    
    .test-actions button {
      padding: 10px 20px;
      border: 1px solid #6c757d;
      background: white;
      border-radius: 4px;
      cursor: pointer;
    }
    
    .test-actions button:hover {
      background: #f8f9fa;
    }
    
    @media (max-width: 768px) {
      .cart-content {
        grid-template-columns: 1fr;
      }
      
      .cart-item {
        grid-template-columns: 1fr;
        gap: 10px;
      }
      
      .item-image {
        display: none;
      }
      
      .cart-summary {
        position: static;
      }
    }
  `]
})
export class CartComponent {
  cartService = inject(CartService);
  promoCode = '';
  
  isCartItem(item: CartItemsObjectResponse): boolean {
    return item.type === 'cart_item' || item.type === 'custom_item';
  }
  
  hasImage(item: CartItemsObjectResponse): boolean {
    return 'image' in item && !!item.image;
  }
  
  getImage(item: CartItemsObjectResponse): any {
    return 'image' in item ? item.image : null;
  }
  
  hasSku(item: CartItemsObjectResponse): boolean {
    return 'sku' in item;
  }
  
  getSku(item: CartItemsObjectResponse): string {
    return 'sku' in item && item.sku ? item.sku : '';
  }
  
  getQuantity(item: CartItemsObjectResponse): number {
    return 'quantity' in item ? item.quantity : 1;
  }
  
  getUnitPrice(item: CartItemsObjectResponse): string {
    if ('meta' in item && item.meta?.display_price?.with_tax) {
      const withTax = item.meta.display_price.with_tax as any;
      if (withTax.unit?.formatted) {
        return withTax.unit.formatted;
      }
    }
    if ('unit_price' in item && item.unit_price?.amount) {
      return `$${(item.unit_price.amount / 100).toFixed(2)}`;
    }
    return '$0.00';
  }
  
  getTotalPrice(item: CartItemsObjectResponse): string {
    if ('meta' in item && item.meta?.display_price?.with_tax) {
      const withTax = item.meta.display_price.with_tax as any;
      if (withTax.value?.formatted) {
        return withTax.value.formatted;
      }
    }
    if ('value' in item && item.value?.amount) {
      return `$${(item.value.amount / 100).toFixed(2)}`;
    }
    return '$0.00';
  }
  
  async updateQuantity(itemId: string, quantity: number) {
    if (quantity < 1) return;
    
    try {
      await this.cartService.updateItemQuantity(itemId, quantity);
    } catch (error) {
      console.error('Failed to update quantity:', error);
    }
  }
  
  async removeItem(itemId: string) {
    if (confirm('Are you sure you want to remove this item?')) {
      try {
        await this.cartService.removeItem(itemId);
      } catch (error) {
        console.error('Failed to remove item:', error);
      }
    }
  }
  
  async applyPromoCode() {
    if (!this.promoCode.trim()) return;
    
    try {
      await this.cartService.applyPromotionCode(this.promoCode);
      this.promoCode = '';
    } catch (error) {
      console.error('Failed to apply promo code:', error);
      alert('Invalid promo code');
    }
  }
  
  async addTestProduct() {
    const testProductId = prompt('Enter a product ID to add to cart:');
    if (!testProductId) return;
    
    try {
      await this.cartService.addToCart(testProductId, 1);
      alert('Product added to cart!');
    } catch (error) {
      console.error('Failed to add product:', error);
      alert('Failed to add product. Make sure the product ID is valid.');
    }
  }
  
  async clearCart() {
    if (confirm('Are you sure you want to clear your cart?')) {
      try {
        await this.cartService.clearCart();
      } catch (error) {
        console.error('Failed to clear cart:', error);
      }
    }
  }
  
  async refreshCart() {
    try {
      await this.cartService.fetchCart();
    } catch (error) {
      console.error('Failed to refresh cart:', error);
    }
  }
}
<div class="cart-container">
  <h1 class="cart-title">Your Cart</h1>
  
  @if ((cartService.loading$ | async)) {
    <div class="loading">Loading cart...</div>
  } @else if ((cartService.error$ | async)) {
    <div class="error">{{ cartService.error$ | async }}</div>
  } @else {
    @let items = cartService.items$ | async;
    @if (items && items.length > 0) {
      <div class="cart-content">
        <div class="cart-items">
          @for (item of items; track getItemId(item)) {
            <div class="cart-item">
              <div class="item-info">
                <h3 class="item-name">{{ getItemName(item) }}</h3>
                @if (getItemDescription(item)) {
                  <p class="item-description">{{ getItemDescription(item) }}</p>
                }
                @if (getItemType(item) === 'subscription_item') {
                  <span class="item-badge">Subscription</span>
                }
              </div>
              
              <div class="item-controls">
                @let itemQuantity = getItemQuantity(item);
                @if (getItemType(item) !== 'subscription_item' && itemQuantity !== undefined) {
                  <div class="quantity-controls">
                    <button 
                      class="quantity-btn" 
                      (click)="updateQuantity(getItemId(item), itemQuantity - 1)"
                      [disabled]="itemQuantity <= 1">
                      -
                    </button>
                    <span class="quantity">{{ itemQuantity }}</span>
                    <button 
                      class="quantity-btn" 
                      (click)="updateQuantity(getItemId(item), itemQuantity + 1)">
                      +
                    </button>
                  </div>
                }
                
                <div class="item-price">
                  {{ getItemPrice(item) }}
                  @let quantity = getItemQuantity(item);
                  @if (quantity && quantity > 1) {
                    <span class="item-total">
                      Total: {{ getItemTotal(item) }}
                    </span>
                  }
                </div>
                
                <button class="remove-btn" (click)="removeItem(getItemId(item))">
                  Remove
                </button>
              </div>
            </div>
          }
        </div>
        
        <div class="cart-summary">
          <h2>Order Summary</h2>
          @let totals = cartService.totals$ | async;
          @if (totals) {
            <div class="summary-line">
              <span>Subtotal</span>
              <span>{{ totals.subtotal }}</span>
            </div>
            
            @if (totals.hasDiscount) {
              <div class="summary-line discount">
                <span>Discount</span>
                <span>{{ totals.discount }}</span>
              </div>
            }
            
            <div class="summary-line">
              <span>Tax</span>
              <span>{{ totals.tax }}</span>
            </div>
            
            <div class="summary-line total">
              <span>Total</span>
              <span>{{ totals.total }}</span>
            </div>
          }
          
          <button class="checkout-btn" (click)="proceedToCheckout()">
            Proceed to Checkout
          </button>
        </div>
      </div>
    } @else {
      <div class="empty-cart">
        <p>Your cart is empty</p>
        <a routerLink="/" class="continue-shopping">Continue Shopping</a>
      </div>
    }
  }
</div>

// thortful-workshop-next/checkpoint-final/src/app/(store)/cart/page.tsx
import Image from "next/image";
import Link from "next/link";
import {getACart} from "@epcc-sdk/sdks-shopper";
import {initializeShopperClient} from "@/lib/epcc-shopper-client";
import {cookies} from "next/headers";
import {CART_COOKIE_KEY} from "@/app/constants";

initializeShopperClient()
export default async function CartPage() {

    const cookieStore = await cookies();
    const cartId = cookieStore.get(CART_COOKIE_KEY)?.value;

    if (!cartId) {
        throw new Error("No cart found");
    }

    const response = await getACart({
        path: { cartID: cartId },
        query: {
            include: ['items', 'tax_items', 'custom_discounts', 'promotions'] as const
        }
    });

    console.log("Cart response:", response.data?.included?.items);

    if (response.error) {
        throw new Error("Failed to fetch cart");
    }

    const items = response.data?.included?.items || [];
    const isEmpty = items.length === 0;

    if (isEmpty) {
        return (
            <div className="max-w-[1200px] mx-auto px-[15px] py-8">
                <h1 className="text-3xl font-bold mb-8">Your Cart</h1>
                <div className="bg-white rounded-lg shadow-sm p-8 text-center">
                    <div className="mb-6">
                        <Image
                            src="/basket-icon.svg"
                            alt="Empty cart"
                            width={64}
                            height={64}
                            className="mx-auto opacity-50"
                        />
                    </div>
                    <h2 className="text-xl font-semibold mb-2">Your cart is empty</h2>
                    <p className="text-gray-600 mb-6">
                        Add some items to your cart to get started.
                    </p>
                    <Link
                        href="/"
                        className="inline-block bg-[#f57c00] text-white px-6 py-3 rounded-lg hover:bg-[#ef6c00] transition-colors"
                    >
                        Continue Shopping
                    </Link>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-[1200px] mx-auto px-[15px] py-8">
            <h1 className="text-3xl font-bold mb-8">Your Cart</h1>

            <div className="grid lg:grid-cols-3 gap-8">
                {/* Cart Items */}
                <div className="lg:col-span-2">
                    <div className="bg-white rounded-lg shadow-sm">
                        <div className="p-6 border-b border-gray-200">
                            <h2 className="text-lg font-semibold">
                                Cart Items ({items.length}{" "}
                                {items.length === 1 ? "item" : "items"})
                            </h2>
                        </div>

                        <div className="p-6">
                            <div className="space-y-6">
                                {items.map((item: any) => (
                                    <div
                                        key={item.id}
                                        className="flex gap-4 pb-6 border-b border-gray-100 last:border-b-0"
                                    >
                                        {/* Product Image */}
                                        <div className="flex-shrink-0">
                                            <div className="w-24 h-24 bg-gray-100 rounded-lg overflow-hidden">
                                                {item.image?.href ? (
                                                    <Image
                                                        src={item.image.href}
                                                        alt={item.name}
                                                        width={96}
                                                        height={96}
                                                        className="w-full h-full object-cover"
                                                    />
                                                ) : (
                                                    <div className="w-full h-full bg-gray-200 flex items-center justify-center">
                                <span className="text-gray-400 text-xs">
                                  No image
                                </span>
                                                    </div>
                                                )}
                                            </div>
                                        </div>

                                        {/* Product Details */}
                                        <div className="flex-grow">
                                            <h3 className="font-semibold text-gray-900 mb-1">
                                                {item.name}
                                            </h3>
                                            {item.description && (
                                                <p className="text-sm text-gray-600 mb-2">
                                                    {item.description}
                                                </p>
                                            )}

                                            <div className="flex items-center gap-4">
                                                <div className="text-lg font-semibold text-[#f57c00]">
                                                    {item.meta.display_price.with_tax.unit.formatted}
                                                </div>

                                                {/* Quantity Controls */}
                                                <div className="flex items-center gap-2">
                                                    <button
                                                        // onClick={() =>
                                                        //     handleQuantityChange(
                                                        //         item.id,
                                                        //         Math.max(1, item.quantity - 1)
                                                        //     )
                                                        // }
                                                        // disabled={isUpdating || item.quantity <= 1}
                                                        className="w-8 h-8 rounded-full border border-gray-300 flex items-center justify-center hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                                                    >
                                                        -
                                                    </button>
                                                    <span className="w-8 text-center font-medium">
                                {item.quantity}
                              </span>
                                                    <button
                                                        // onClick={() =>
                                                        //     handleQuantityChange(
                                                        //         item.id,
                                                        //         item.quantity + 1
                                                        //     )
                                                        // }
                                                        // disabled={isUpdating}
                                                        className="w-8 h-8 rounded-full border border-gray-300 flex items-center justify-center hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                                                    >
                                                        +
                                                    </button>
                                                </div>

                                                {/* Remove Button */}
                                                <button
                                                    // onClick={() => handleRemoveItem(item.id)}
                                                    // disabled={isUpdating}
                                                    className="text-sm text-red-600 hover:text-red-800 disabled:opacity-50 disabled:cursor-not-allowed"
                                                >
                                                    Remove
                                                </button>
                                            </div>

                                            {/* Line Total */}
                                            <div className="mt-2 text-right">
                            <span className="font-semibold">
                              {item.meta.display_price.with_tax.value.formatted}
                            </span>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Cart Summary */}
                <div className="lg:col-span-1">
                    <div className="bg-white rounded-lg shadow-sm p-6 sticky top-4">
                        <h2 className="text-lg font-semibold mb-4">Order Summary</h2>

                        <div className="space-y-3 mb-6">
                            <div className="flex justify-between">
                                <span>Subtotal</span>
                                <span>
                      {response.data?.data?.meta?.display_price?.without_tax?.formatted}
                    </span>
                            </div>

                            {response.data?.data?.meta?.display_price?.tax && (
                                <div className="flex justify-between">
                                    <span>Tax</span>
                                    <span>{response.data?.data?.meta?.display_price?.tax?.formatted}</span>
                                </div>
                            )}

                            <div className="border-t border-gray-200 pt-3">
                                <div className="flex justify-between font-semibold text-lg">
                                    <span>Total</span>
                                    <span className="text-[#f57c00]">
                        {response.data?.data?.meta?.display_price?.with_tax?.formatted}
                      </span>
                                </div>
                            </div>
                            <Link href="/checkout">
                                <button
                                    type="button"
                                    // disabled={isUpdating}
                                    className="w-full bg-[#f57c00] text-white py-3 px-4 rounded-lg font-semibold hover:bg-[#ef6c00] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    Proceed to Checkout
                                    {/*{isUpdating ? "Updating..." : "Proceed to Checkout"}*/}
                                </button>
                            </Link>
                            <Link
                                href="/"
                                className="block text-center text-[#f57c00] hover:text-[#ef6c00] mt-4 transition-colors"
                            >
                                Continue Shopping
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
